Repository dasha-korotkykh/dariakorotkykh.com, pull requests merged in 2019-03, with the labels that each got.

#85 Implement fixes proposed by Grammarly, remove "budget" from Binary Studio section
  index.html
Labels: enhancement

#87 Restyle events
  index.html
Labels: release

#88 Updated and reordered secondary column content
  index.html
Labels: enhancement

#89 Update events and secondary content
  index.html
Labels: enhancement, release

#90 Really minor punctuation changes
  index.html
Labels: release

#92 Fix class names, refactor LANGUAGE block, restyle highlighted items
  index.html
Labels: bug, enhancement

#93 Edited Binary Studio experience
  index.html
Labels: enhancement

#94 Update index.html
  index.html
Labels: bug

#95 Added Character block
  assets/sounds/are-you-not-entertained.mp3
  index.html
Labels: enhancement

#97 Use volodymyrkushnir.com's styles for audio button, update Day to day block, switch Goals and Tools
  index.html
Labels: enhancement

#99 Refactor .events
  index.html
Labels: bug

#100 Minor changes
  index.html
Labels: enhancement

#102 Add LICENSE
  LICENSE
Labels: release

#103 Update favicons and avatar
  assets/images/apple-touch-icon.png
  assets/images/avatar.svg
  assets/images/favicon-192x192.png
  assets/images/favicon-512x512.png
  assets/images/favicon.ico
  favicon.ico
Labels: enhancement

#104 Add empty SKILLS block, move CREDENTIALS higher
  index.html
Labels: enhancement

#105 Refactored secondary column
  index.html
Labels: enhancement
