Repository dasha-korotkykh/dariakorotkykh.com, pull requests merged in 2019-02, with the labels that each got.

#51 Conform to new CSS on volodymyrkushnir.com
  .gitignore
  index.html
Labels: bug

#52 Rename #desktop to #pages
  index.html
Labels: bug

#53 Timeline refactoring and personality blocks content update (closes #14, closes #36, closes #43, closes #45, closes #48, closes #49)
  index.html
Labels: enhancement, release

#54 Content update
  index.html
Labels: enhancement

#57 Changed contacts (closes #55)
  index.html
Labels: enhancement

#59 Update content
  index.html
Labels: enhancement

#60 Restyle timeline
  .DS_Store
  assets/.DS_Store
  assets/images/.DS_Store
  index.html
Labels: enhancement

#61 Restyle timeline, make it interactive
  index.html
Labels: enhancement

#62 Restyle timeline
  index.html
Labels: enhancement

#63 Jam/Hackathon block descriptions
  index.html
Labels: enhancement

#66 Update avatar background color
  assets/images/avatar.png
  assets/images/avatar.svg
Labels: enhancement

#67 Add wave, add credits, restyle tags
  index.html
Labels: enhancement

#68 Switch to article and section instead of divs
  index.html
Labels: enhancement

#82 Update Education
  index.html
Labels: enhancement

#83 Restructure, reformat, grammar and spellcheck
  index.html
Labels: enhancement

#84 Restructure, reformat, grammar and spellcheck
  index.html
Labels: enhancement
